# Generated by Django 5.1.6 on 2025-03-27 03:45

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id_hotline', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID unik untuk layanan hotline', primary_key=True, serialize=False)),
                ('nama', models.CharField(help_text='Nama layanan hotline', max_length=100, validators=[django.core.validators.RegexValidator(message='Nama hanya boleh mengandung huruf, angka, spasi, dan tanda hubung', regex='^[a-zA-Z0-9\\s\\-]+$')])),
                ('nomor_telepon', models.CharField(help_text='Nomor telepon hotline (contoh: 110, 112, 113, dll)', max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor telepon harus berupa angka (3-15 digit)', regex='^\\d{3,15}$')])),
                ('alamat', models.TextField(help_text='Alamat kantor layanan hotline', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Website resmi layanan (opsional)', null=True)),
                ('layanan', models.TextField(help_text='Deskripsi layanan yang disediakan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotline',
                'verbose_name_plural': 'Hotline',
                'ordering': ['nama'],
            },
        ),
    ]
