# Generated by Django 5.1.6 on 2025-03-23 15:27

import os
from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()


def create_superuser(apps, schema_editor):
    
    # Check if the superuser already exists
    if not User.objects.filter(username=os.environ.get('SUPERUSER_USERNAME')).exists():
        User.objects.create_superuser(
            username=os.environ.get('SUPERUSER_USERNAME'),
            email=os.environ.get('SUPERUSER_EMAIL'),
            password=os.environ.get('SUPERUSER_PASSWORD'),
            name=os.environ.get('SUPERUSER_NAME'),
            nomor_telepon=os.environ.get('SUPERUSER_TELEPON')
        )
        print('Superuser created successfully')
    else:
        print('Superuser already exists, skipping creation')

def delete_superuser(apps, schema_editor):
    try:
        User.objects.get(username=os.environ.get('SUPERUSER_USERNAME')).delete()
        print('Superuser deleted successfully')
    except:
        print('Superuser not found, skipping deletion')

class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
        ('api_auth', '0003_alter_user_password_salt'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
