# Generated by Django 5.1.6 on 2025-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default='vn01nqh648j+znGa1bbk1VMIHAplLBPjMOdGHgqCFMI=', max_length=64),
        ),
    ]
