# Generated by Django 5.1.6 on 2025-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_user_password_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_salt',
            field=models.CharField(max_length=64),
        ),
    ]
