# Generated by Django 5.1.6 on 2025-03-24 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Name is only allowed to contain letters and spaces. Nama hanya boleh berisi huruf dan spasi', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'User with this username already exists. User dengan username ini sudah ada.'}, max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Username is only allowed to contain letters, numbers, and the following characters: (.),(_),(-). Username hanya boleh berisi huruf, angka, dan karakter berikut: (.),(_),(-).', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
