# Generated by Django 5.1.6 on 2025-03-26 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-tanggal_publikasi'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='id',
        ),
        migrations.AddField(
            model_name='artikel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artikel',
            name='id_artikel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.CharField(choices=[('umum', 'Umum'), ('berita', 'Berita'), ('pengumuman', 'Pengumuman'), ('tips', 'Tips & Tricks'), ('tutorial', 'Tutorial'), ('event', 'Event')], default='umum', max_length=20),
        ),
        migrations.AddField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=15),
        ),
        migrations.AddField(
            model_name='artikel',
            name='tampilan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artikel',
            name='tanggal_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('disetujui', models.BooleanField(default=False)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='api_article.artikel')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('artikel', models.ManyToManyField(related_name='tags', to='api_article.artikel')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['nama'],
            },
        ),
    ]
